sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
wechat:
  appid: wx11f7015b3768cd5f
  secret: b0f33fdc5a94dee0f66d7ffea10878e6